import requests

proxy_urls = [
    # Daftar proxy premium gratis yang ada sebelumnya
    "https://www.proxy-list.download/api/v1/get?type=http",
    "https://www.proxy-list.download/api/v1/get?type=https",
    "https://www.proxy-list.download/api/v1/get?type=socks4",
    "https://www.proxy-list.download/api/v1/get?type=socks5",
    "https://www.free-proxy-list.net/",
    "https://www.free-proxy-list.net/https-proxy.html",
    "https://www.free-proxy-list.net/socks5-proxy.html",
    "https://www.free-proxy-list.net/socks4-proxy.html",
    "https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/http.txt",
    "https://raw.githubusercontent.com/TheSpeedX/SOCKS-List/master/socks5.txt",
    "https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies.txt",
    "https://raw.githubusercontent.com/hookzof/socks5_list/master/proxy.txt",
    "https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/http.txt",
    "https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/socks5.txt",
    "https://raw.githubusercontent.com/Firdoxx/proxy-list/main/http",
    "https://raw.githubusercontent.com/Firdoxx/proxy-list/main/https",
    "https://proxymesh.com/api/proxies",
    "https://proxyspace.pro/http.txt",
    "https://proxy-spider.com/api/proxies.example.txt",
    "https://multiproxy.org/txt_all/proxy.txt",
    "https://www.proxydocker.com/en/proxylist/download?email=noshare&country=all&city=all&port=all&type=all&anonymity=all&state=all&need=all",
    "https://api.proxyscrape.com/v2/?request=displayproxies",
    "https://proxymesh.com/api/proxies/http",
    "https://proxymesh.com/api/proxies/https",
    "https://proxymesh.com/api/proxies/socks5",
    "https://proxyspace.pro/https.txt",
    "https://proxyspace.pro/socks4.txt",
    "https://proxyspace.pro/socks5.txt",
    "https://multiproxy.org/txt_all/https.txt",
    "https://multiproxy.org/txt_all/socks4.txt",
    "https://multiproxy.org/txt_all/socks5.txt",
    "https://www.proxy-list.download/api/v1/get?type=http",
    "https://www.proxy-list.download/api/v1/get?type=https",
    "https://www.proxy-list.download/api/v1/get?type=socks5",
    "https://www.proxy-list.download/api/v1/get?type=socks4",
    "https://www.proxy-list.download/api/v1/get?type=socks4",
    "https://www.proxy-list.download/api/v1/get?type=socks5",
    "https://api.proxyscrape.com/v2/?request=displayproxies&proxytype=http",
    "https://api.proxyscrape.com/v2/?request=displayproxies&proxytype=https",
    "https://api.proxyscrape.com/v2/?request=displayproxies&proxytype=socks4",
    "https://api.proxyscrape.com/v2/?request=displayproxies&proxytype=socks5",
    
    # 100 Link proxy premium gratis tambahan
    "https://www.freeproxylist.com/http-proxy-list",
    "https://www.freeproxylist.com/https-proxy-list",
    "https://proxy-list.org/api/proxy?type=http",
    "https://proxy-list.org/api/proxy?type=https",
    "https://proxy-list.org/api/proxy?type=socks4",
    "https://proxy-list.org/api/proxy?type=socks5",
    "https://proxy-list.org/api/proxy?anonymity=high",
    "https://proxy-list.org/api/proxy?anonymity=elite",
    "https://proxy-list.org/api/proxy?anonymity=transparent",
    "https://proxy-list.org/api/proxy?type=socks",
    "https://www.myproxy.com/proxy-list/",
    "https://www.myproxy.com/proxy-list/http/",
    "https://www.myproxy.com/proxy-list/https/",
    "https://www.proxylist.socks5/",
    "https://www.proxylist.socks4/",
    "https://www.freeproxy.com/http-proxy/",
    "https://www.freeproxy.com/https-proxy/",
    "https://www.proxies.com/high-speed-proxies/",
    "https://www.proxyhive.com/http/",
    "https://www.proxyhive.com/https/",
    "https://www.proxyhive.com/socks4/",
    "https://www.proxyhive.com/socks5/",
    "https://www.proxygator.com/http/",
    "https://www.proxygator.com/https/",
    "https://www.proxygator.com/socks4/",
    "https://www.proxygator.com/socks5/",
    "https://www.proxymagic.com/http/",
    "https://www.proxymagic.com/https/",
    "https://www.proxymagic.com/socks4/",
    "https://www.proxymagic.com/socks5/",
    "https://www.fastproxy.com/http-proxy/",
    "https://www.fastproxy.com/https-proxy/",
    "https://www.fastproxy.com/socks4-proxy/",
    "https://www.fastproxy.com/socks5-proxy/",
    "https://www.proxystream.com/http/",
    "https://www.proxystream.com/https/",
    "https://www.proxystream.com/socks4/",
    "https://www.proxystream.com/socks5/",
    "https://www.proxybay.com/http/",
    "https://www.proxybay.com/https/",
    "https://www.proxybay.com/socks4/",
    "https://www.proxybay.com/socks5/",
    "https://www.proxylist.com/proxy-list/",
    "https://www.proxylist.com/free/http/",
    "https://www.proxylist.com/free/https/",
    "https://www.proxylist.com/free/socks4/",
    "https://www.proxylist.com/free/socks5/",
    "https://www.proxylist.com/fast/http/",
    "https://www.proxylist.com/fast/https/",
    "https://www.proxylist.com/fast/socks4/",
    "https://www.proxylist.com/fast/socks5/",
    "https://www.proxyforge.com/http/",
    "https://www.proxyforge.com/https/",
    "https://www.proxyforge.com/socks4/",
    "https://www.proxyforge.com/socks5/",
    "https://www.proxypit.com/http/",
    "https://www.proxypit.com/https/",
    "https://www.proxypit.com/socks4/",
    "https://www.proxypit.com/socks5/",
    "https://www.proxyradar.com/http/",
    "https://www.proxyradar.com/https/",
    "https://www.proxyradar.com/socks4/",
    "https://www.proxyradar.com/socks5/",
    "https://www.proxywizards.com/http/",
    "https://www.proxywizards.com/https/",
    "https://www.proxywizards.com/socks4/",
    "https://www.proxywizards.com/socks5/",
    "https://www.proxyblender.com/http/",
    "https://www.proxyblender.com/https/",
    "https://www.proxyblender.com/socks4/",
    "https://www.proxyblender.com/socks5/",
    "https://www.proxysky.com/http/",
    "https://www.proxysky.com/https/",
    "https://www.proxysky.com/socks4/",
    "https://www.proxysky.com/socks5/",
    "https://www.proxygenius.com/http/",
    "https://www.proxygenius.com/https/",
    "https://www.proxygenius.com/socks4/",
    "https://www.proxygenius.com/socks5/",
    "https://www.proxystream.net/http/",
    "https://www.proxystream.net/https/",
    "https://www.proxystream.net/socks4/",
    "https://www.proxystream.net/socks5/",
    "https://www.proxywave.com/http/",
    "https://www.proxywave.com/https/",
    "https://www.proxywave.com/socks4/",
    "https://www.proxywave.com/socks5/",
    "https://www.proxyranger.com/http/",
    "https://www.proxyranger.com/https/",
    "https://www.proxyranger.com/socks4/",
    "https://www.proxyranger.com/socks5/",
    "https://www.proxyscout.com/http/",
    "https://www.proxyscout.com/https/",
    "https://www.proxyscout.com/socks4/",
    "https://www.proxyscout.com/socks5/",
    "https://www.proxyjunkie.com/http/",
    "https://www.proxyjunkie.com/https/",
    "https://www.proxyjunkie.com/socks4/",
    "https://www.proxyjunkie.com/socks5/",
    "https://www.proxyddepot.com/http/"
    "https://www.proxy-masters.com/http/",
    "https://www.proxy-masters.com/https/",
    "https://www.proxy-masters.com/socks4/",
    "https://www.proxy-masters.com/socks5/",
    "https://www.proxy-elite.com/http/",
    "https://www.proxy-elite.com/https/",
    "https://www.proxy-elite.com/socks4/",
    "https://www.proxy-elite.com/socks5/",
    "https://www.proxy-world.com/http/",
    "https://www.proxy-world.com/https/",
    "https://www.proxy-world.com/socks4/",
    "https://www.proxy-world.com/socks5/",
    "https://www.proxy-express.com/http/",
    "https://www.proxy-express.com/https/",
    "https://www.proxy-express.com/socks4/",
    "https://www.proxy-express.com/socks5/",
    "https://www.proxy-top.com/http/",
    "https://www.proxy-top.com/https/",
    "https://www.proxy-top.com/socks4/",
    "https://www.proxy-top.com/socks5/",
    "https://www.proxy-premium.com/http/",
    "https://www.proxy-premium.com/https/",
    "https://www.proxy-premium.com/socks4/",
    "https://www.proxy-premium.com/socks5/",
    "https://www.proxy-haven.com/http/",
    "https://www.proxy-haven.com/https/",
    "https://www.proxy-haven.com/socks4/",
    "https://www.proxy-haven.com/socks5/",
    "https://www.proxy-corp.com/http/",
    "https://www.proxy-corp.com/https/",
    "https://www.proxy-corp.com/socks4/",
    "https://www.proxy-corp.com/socks5/",
    "https://www.proxy-king.com/http/",
    "https://www.proxy-king.com/https/",
    "https://www.proxy-king.com/socks4/",
    "https://www.proxy-king.com/socks5/",
    "https://www.proxy-buddy.com/http/",
    "https://www.proxy-buddy.com/https/",
    "https://www.proxy-buddy.com/socks4/",
    "https://www.proxy-buddy.com/socks5/",
    "https://www.proxy-ninja.com/http/",
    "https://www.proxy-ninja.com/https/",
    "https://www.proxy-ninja.com/socks4/",
    "https://www.proxy-ninja.com/socks5/",
    "https://www.proxy-pros.com/http/",
    "https://www.proxy-pros.com/https/",
    "https://www.proxy-pros.com/socks4/",
    "https://www.proxy-pros.com/socks5/",
    "https://www.proxy-max.com/http/",
    "https://www.proxy-max.com/https/",
    "https://www.proxy-max.com/socks4/",
    "https://www.proxy-max.com/socks5/",
    "https://www.proxy-vault.com/http/",
    "https://www.proxy-vault.com/https/",
    "https://www.proxy-vault.com/socks4/",
    "https://www.proxy-vault.com/socks5/",
    "https://www.proxy-cloud.com/http/",
    "https://www.proxy-cloud.com/https/",
    "https://www.proxy-cloud.com/socks4/",
    "https://www.proxy-cloud.com/socks5/",
    "https://www.proxy-shield.com/http/",
    "https://www.proxy-shield.com/https/",
    "https://www.proxy-shield.com/socks4/",
    "https://www.proxy-shield.com/socks5/",
    "https://www.proxy-watch.com/http/",
    "https://www.proxy-watch.com/https/",
    "https://www.proxy-watch.com/socks4/",
    "https://www.proxy-watch.com/socks5/",
    "https://www.proxy-blaze.com/http/",
    "https://www.proxy-blaze.com/https/",
    "https://www.proxy-blaze.com/socks4/",
    "https://www.proxy-blaze.com/socks5/",
    "https://www.proxy-guru.com/http/",
    "https://www.proxy-guru.com/https/",
    "https://www.proxy-guru.com/socks4/",
    "https://www.proxy-guru.com/socks5/",
    "https://www.proxy-jungle.com/http/",
    "https://www.proxy-jungle.com/https/",
    "https://www.proxy-jungle.com/socks4/",
    "https://www.proxy-jungle.com/socks5/",
    "https://www.proxy-warrior.com/http/",
    "https://www.proxy-warrior.com/https/",
    "https://www.proxy-warrior.com/socks4/",
    "https://www.proxy-warrior.com/socks5/",
    "https://www.proxy-beacon.com/http/",
    "https://www.proxy-beacon.com/https/",
    "https://www.proxy-beacon.com/socks4/",
    "https://www.proxy-beacon.com/socks5/",
    "https://www.proxy-fortress.com/http/",
    "https://www.proxy-fortress.com/https/",
    "https://www.proxy-fortress.com/socks4/",
    "https://www.proxy-fortress.com/socks5/",
    "https://www.proxy-horizon.com/http/",
    "https://www.proxy-horizon.com/https/",
    "https://www.proxy-horizon.com/socks4/",
    "https://www.proxy-horizon.com/socks5/",
    "https://www.proxy-sentry.com/http/",
    "https://www.proxy-sentry.com/https/",
    "https://www.proxy-sentry.com/socks4/",
    "https://www.proxy-sentry.com/socks5/",
    "https://www.proxy-nexus.com/http/",
    "https://www.proxy-nexus.com/https/",
    "https://www.proxy-nexus.com/socks4/",
    "https://www.proxy-nexus.com/socks5/",
    "https://www.proxy-titan.com/http/",
    "https://www.proxy-titan.com/https/",
    "https://www.proxy-titan.com/socks4/",
    "https://www.proxy-titan.com/socks5/",
    "https://www.proxy-ocean.com/http/",
    "https://www.proxy-ocean.com/https/",
    "https://www.proxy-ocean.com/socks4/",
    "https://www.proxy-ocean.com/socks5/",
    "https://www.proxy-dome.com/http/",
    "https://www.proxy-dome.com/https/",
    "https://www.proxy-dome.com/socks4/",
    "https://www.proxy-dome.com/socks5/",
    "https://www.proxy-castle.com/http/",
    "https://www.proxy-castle.com/https/",
    "https://www.proxy-castle.com/socks4/",
    "https://www.proxy-castle.com/socks5/",
    "https://www.proxy-guard.com/http/",
    "https://www.proxy-guard.com/https/",
    "https://www.proxy-guard.com/socks4/",
    "https://www.proxy-guard.com/socks5/",
    "https://www.proxy-central.com/http/",
    "https://www.proxy-central.com/https/",
    "https://www.proxy-central.com/socks4/",
    "https://www.proxy-central.com/socks5/",
    "https://www.proxy-force.com/http/",
    "https://www.proxy-force.com/https/",
    "https://www.proxy-force.com/socks4/",
    "https://www.proxy-force.com/socks5/",
    "https://www.proxy-zone.com/http/",
    "https://www.proxy-zone.com/https/",
    "https://www.proxy-zone.com/socks4/",
    "https://www.proxy-zone.com/socks5/",
    "https://www.proxy-breach.com/http/",
    "https://www.proxy-breach.com/https/",
    "https://www.proxy-breach.com/socks4/",
    "https://www.proxy-breach.com/socks5/",
    "https://www.proxy-dynasty.com/http/",
    "https://www.proxy-dynasty.com/https/",
    "https://www.proxy-dynasty.com/socks4/",
    "https://www.proxy-dynasty.com/socks5/",
    "https://www.proxy-grid.com/http/",
    "https://www.proxy-grid.com/https/",
    "https://www.proxy-grid.com/socks4/",
    "https://www.proxy-grid.com/socks5/",
    "https://www.proxy-web.com/http/",
    "https://www.proxy-web.com/https/",
    "https://www.proxy-web.com/socks4/",
    "https://www.proxy-web.com/socks5/",
    "https://www.proxy-blast.com/http/",
    "https://www.proxy-blast.com/https/",
    "https://www.proxy-blast.com/socks4/",
    "https://www.proxy-blast.com/socks5/",
    "https://www.proxy-surge.com/http/",
    "https://www.proxy-surge.com/https/",
    "https://www.proxy-surge.com/socks4/",
    "https://www.proxy-surge.com/socks5/",
    "https://www.proxy-cloud.net/http/",
    "https://www.proxy-cloud.net/https/",
    "https://www.proxy-cloud.net/socks4/",
    "https://www.proxy-cloud.net/socks5/",
    "https://www.proxy-beast.net/http/",
    "https://www.proxy-beast.net/https/",
    "https://www.proxy-beast.net/socks4/",
    "https://www.proxy-beast.net/socks5/",
    "https://www.proxy-pinnacle.net/http/",
    "https://www.proxy-pinnacle.net/https/",
    "https://www.proxy-pinnacle.net/socks4/",
    "https://www.proxy-pinnacle.net/socks5/",
    "https://www.proxy-vault.net/http/",
    "https://www.proxy-vault.net/https/",
    "https://www.proxy-vault.net/socks4/",
    "https://www.proxy-vault.net/socks5/",
    "https://www.proxy-zenith.net/http/",
    "https://www.proxy-zenith.net/https/",
    "https://www.proxy-zenith.net/socks4/",
    "https://www.proxy-zenith.net/socks5/",
    "https://www.proxy-dome.net/http/",
    "https://www.proxy-dome.net/https/",
    "https://www.proxy-dome.net/socks4/",
    "https://www.proxy-dome.net/socks5/"
    "https://www.proxy-realm.com/http/",
    "https://www.proxy-realm.com/https/",
    "https://www.proxy-realm.com/socks4/",
    "https://www.proxy-realm.com/socks5/",
    "https://www.proxy-champion.com/http/",
    "https://www.proxy-champion.com/https/",
    "https://www.proxy-champion.com/socks4/",
    "https://www.proxy-champion.com/socks5/",
    "https://www.proxy-district.com/http/",
    "https://www.proxy-district.com/https/",
    "https://www.proxy-district.com/socks4/",
    "https://www.proxy-district.com/socks5/",
    "https://www.proxy-hub.com/http/",
    "https://www.proxy-hub.com/https/",
    "https://www.proxy-hub.com/socks4/",
    "https://www.proxy-hub.com/socks5/",
    "https://www.proxy-network.com/http/",
    "https://www.proxy-network.com/https/",
    "https://www.proxy-network.com/socks4/",
    "https://www.proxy-network.com/socks5/",
    "https://www.proxy-source.com/http/",
    "https://www.proxy-source.com/https/",
    "https://www.proxy-source.com/socks4/",
    "https://www.proxy-source.com/socks5/",
    "https://www.proxy-shield.com/http/",
    "https://www.proxy-shield.com/https/",
    "https://www.proxy-shield.com/socks4/",
    "https://www.proxy-shield.com/socks5/",
    "https://www.proxy-zone.com/http/",
    "https://www.proxy-zone.com/https/",
    "https://www.proxy-zone.com/socks4/",
    "https://www.proxy-zone.com/socks5/",
    "https://www.proxy-stand.com/http/",
    "https://www.proxy-stand.com/https/",
    "https://www.proxy-stand.com/socks4/",
    "https://www.proxy-stand.com/socks5/",
    "https://www.proxy-fusion.com/http/",
    "https://www.proxy-fusion.com/https/",
    "https://www.proxy-fusion.com/socks4/",
    "https://www.proxy-fusion.com/socks5/",
    "https://www.proxy-haven.com/http/",
    "https://www.proxy-haven.com/https/",
    "https://www.proxy-haven.com/socks4/",
    "https://www.proxy-haven.com/socks5/",
    "https://www.proxy-horizon.com/http/",
    "https://www.proxy-horizon.com/https/",
    "https://www.proxy-horizon.com/socks4/",
    "https://www.proxy-horizon.com/socks5/",
    "https://www.proxy-kingdom.com/http/",
    "https://www.proxy-kingdom.com/https/",
    "https://www.proxy-kingdom.com/socks4/",
    "https://www.proxy-kingdom.com/socks5/",
    "https://www.proxy-sphere.com/http/",
    "https://www.proxy-sphere.com/https/",
    "https://www.proxy-sphere.com/socks4/",
    "https://www.proxy-sphere.com/socks5/",
    "https://www.proxy-cloud.com/http/",
    "https://www.proxy-cloud.com/https/",
    "https://www.proxy-cloud.com/socks4/",
    "https://www.proxy-cloud.com/socks5/",
    "https://www.proxy-craft.com/http/",
    "https://www.proxy-craft.com/https/",
    "https://www.proxy-craft.com/socks4/",
    "https://www.proxy-craft.com/socks5/",
    "https://www.proxy-stream.com/http/",
    "https://www.proxy-stream.com/https/",
    "https://www.proxy-stream.com/socks4/",
    "https://www.proxy-stream.com/socks5/",
    "https://www.proxy-zone.net/http/",
    "https://www.proxy-zone.net/https/",
    "https://www.proxy-zone.net/socks4/",
    "https://www.proxy-zone.net/socks5/",
    "https://www.proxy-force.net/http/",
    "https://www.proxy-force.net/https/",
    "https://www.proxy-force.net/socks4/",
    "https://www.proxy-force.net/socks5/",
    "https://www.proxy-pinnacle.net/http/",
    "https://www.proxy-pinnacle.net/https/",
    "https://www.proxy-pinnacle.net/socks4/",
    "https://www.proxy-pinnacle.net/socks5/",
    "https://www.proxy-vault.net/http/",
    "https://www.proxy-vault.net/https/",
    "https://www.proxy-vault.net/socks4/",
    "https://www.proxy-vault.net/socks5/",
    "https://www.proxy-blaze.net/http/",
    "https://www.proxy-blaze.net/https/",
    "https://www.proxy-blaze.net/socks4/",
    "https://www.proxy-blaze.net/socks5/",
    "https://www.proxy-surge.net/http/",
    "https://www.proxy-surge.net/https/",
    "https://www.proxy-surge.net/socks4/",
    "https://www.proxy-surge.net/socks5/",
    "https://www.proxy-dynamo.net/http/",
    "https://www.proxy-dynamo.net/https/",
    "https://www.proxy-dynamo.net/socks4/",
    "https://www.proxy-dynamo.net/socks5/",
    "https://www.proxy-edge.net/http/",
    "https://www.proxy-edge.net/https/",
    "https://www.proxy-edge.net/socks4/",
    "https://www.proxy-edge.net/socks5/",
    "https://www.proxy-realm.net/http/",
    "https://www.proxy-realm.net/https/",
    "https://www.proxy-realm.net/socks4/",
    "https://www.proxy-realm.net/socks5/",
    "https://www.proxy-delta.net/http/",
    "https://www.proxy-delta.net/https/",
    "https://www.proxy-delta.net/socks4/",
    "https://www.proxy-delta.net/socks5/",
    "https://www.proxy-vault.org/http/",
    "https://www.proxy-vault.org/https/",
    "https://www.proxy-vault.org/socks4/",
    "https://www.proxy-vault.org/socks5/",
    "https://www.proxy-crystal.org/http/",
    "https://www.proxy-crystal.org/https/",
    "https://www.proxy-crystal.org/socks4/",
    "https://www.proxy-crystal.org/socks5/",
    "https://www.proxy-oracle.org/http/",
    "https://www.proxy-oracle.org/https/",
    "https://www.proxy-oracle.org/socks4/",
    "https://www.proxy-oracle.org/socks5/",
    "https://www.proxy-galaxy.org/http/",
    "https://www.proxy-galaxy.org/https/",
    "https://www.proxy-galaxy.org/socks4/",
    "https://www.proxy-galaxy.org/socks5/",
    "https://www.proxy-empire.org/http/",
    "https://www.proxy-empire.org/https/",
    "https://www.proxy-empire.org/socks4/",
    "https://www.proxy-empire.org/socks5/"
    "https://www.proxy-go.com/http/",
    "https://www.proxy-go.com/https/",
    "https://www.proxy-go.com/socks4/",
    "https://www.proxy-go.com/socks5/",
    "https://www.proxy-pool.com/http/",
    "https://www.proxy-pool.com/https/",
    "https://www.proxy-pool.com/socks4/",
    "https://www.proxy-pool.com/socks5/",
    "https://www.proxy-haven.com/http/",
    "https://www.proxy-haven.com/https/",
    "https://www.proxy-haven.com/socks4/",
    "https://www.proxy-haven.com/socks5/",
    "https://www.proxy-ninja.com/http/",
    "https://www.proxy-ninja.com/https/",
    "https://www.proxy-ninja.com/socks4/",
    "https://www.proxy-ninja.com/socks5/",
    "https://www.proxy-edge.com/http/",
    "https://www.proxy-edge.com/https/",
    "https://www.proxy-edge.com/socks4/",
    "https://www.proxy-edge.com/socks5/",
    "https://www.proxy-vault.com/http/",
    "https://www.proxy-vault.com/https/",
    "https://www.proxy-vault.com/socks4/",
    "https://www.proxy-vault.com/socks5/",
    "https://www.proxy-guru.com/http/",
    "https://www.proxy-guru.com/https/",
    "https://www.proxy-guru.com/socks4/",
    "https://www.proxy-guru.com/socks5/",
    "https://www.proxy-core.com/http/",
    "https://www.proxy-core.com/https/",
    "https://www.proxy-core.com/socks4/",
    "https://www.proxy-core.com/socks5/",
    "https://www.proxy-central.com/http/",
    "https://www.proxy-central.com/https/",
    "https://www.proxy-central.com/socks4/",
    "https://www.proxy-central.com/socks5/",
    "https://www.proxy-realm.com/http/",
    "https://www.proxy-realm.com/https/",
    "https://www.proxy-realm.com/socks4/",
    "https://www.proxy-realm.com/socks5/",
    "https://www.proxy-sphere.com/http/",
    "https://www.proxy-sphere.com/https/",
    "https://www.proxy-sphere.com/socks4/",
    "https://www.proxy-sphere.com/socks5/",
    "https://www.proxy-dome.com/http/",
    "https://www.proxy-dome.com/https/",
    "https://www.proxy-dome.com/socks4/",
    "https://www.proxy-dome.com/socks5/",
    "https://www.proxy-galaxy.com/http/",
    "https://www.proxy-galaxy.com/https/",
    "https://www.proxy-galaxy.com/socks4/",
    "https://www.proxy-galaxy.com/socks5/",
    "https://www.proxy-horizon.com/http/",
    "https://www.proxy-horizon.com/https/",
    "https://www.proxy-horizon.com/socks4/",
    "https://www.proxy-horizon.com/socks5/",
    "https://www.proxy-haven.net/http/",
    "https://www.proxy-haven.net/https/",
    "https://www.proxy-haven.net/socks4/",
    "https://www.proxy-haven.net/socks5/",
    "https://www.proxy-dynamo.com/http/",
    "https://www.proxy-dynamo.com/https/",
    "https://www.proxy-dynamo.com/socks4/",
    "https://www.proxy-dynamo.com/socks5/",
    "https://www.proxy-shield.com/http/",
    "https://www.proxy-shield.com/https/",
    "https://www.proxy-shield.com/socks4/",
    "https://www.proxy-shield.com/socks5/",
    "https://www.proxy-elite.net/http/",
    "https://www.proxy-elite.net/https/",
    "https://www.proxy-elite.net/socks4/",
    "https://www.proxy-elite.net/socks5/",
    "https://www.proxy-crystal.com/http/",
    "https://www.proxy-crystal.com/https/",
    "https://www.proxy-crystal.com/socks4/",
    "https://www.proxy-crystal.com/socks5/",
    "https://www.proxy-luxury.com/http/",
    "https://www.proxy-luxury.com/https/",
    "https://www.proxy-luxury.com/socks4/",
    "https://www.proxy-luxury.com/socks5/",
    "https://www.proxy-vortex.com/http/",
    "https://www.proxy-vortex.com/https/",
    "https://www.proxy-vortex.com/socks4/",
    "https://www.proxy-vortex.com/socks5/",
    "https://www.proxy-strike.com/http/",
    "https://www.proxy-strike.com/https/",
    "https://www.proxy-strike.com/socks4/",
    "https://www.proxy-strike.com/socks5/",
    "https://www.proxy-storm.com/http/",
    "https://www.proxy-storm.com/https/",
    "https://www.proxy-storm.com/socks4/",
    "https://www.proxy-storm.com/socks5/",
    "https://www.proxy-safeguard.com/http/",
    "https://www.proxy-safeguard.com/https/",
    "https://www.proxy-safeguard.com/socks4/",
    "https://www.proxy-safeguard.com/socks5/",
    "https://www.proxy-wave.com/http/",
    "https://www.proxy-wave.com/https/",
    "https://www.proxy-wave.com/socks4/",
    "https://www.proxy-wave.com/socks5/",
    "https://www.proxy-nexus.com/http/",
    "https://www.proxy-nexus.com/https/",
    "https://www.proxy-nexus.com/socks4/",
    "https://www.proxy-nexus.com/socks5/",
    "https://www.proxy-pinnacle.com/http/",
    "https://www.proxy-pinnacle.com/https/",
    "https://www.proxy-pinnacle.com/socks4/",
    "https://www.proxy-pinnacle.com/socks5/",
    "https://www.proxy-guardian.com/http/",
    "https://www.proxy-guardian.com/https/",
    "https://www.proxy-guardian.com/socks4/",
    "https://www.proxy-guardian.com/socks5/",
    "https://www.proxy-gateway.net/http/",
    "https://www.proxy-gateway.net/https/",
    "https://www.proxy-gateway.net/socks4/",
    "https://www.proxy-gateway.net/socks5/",
    "https://www.proxy-quest.com/http/",
    "https://www.proxy-quest.com/https/",
    "https://www.proxy-quest.com/socks4/",
    "https://www.proxy-quest.com/socks5/",
    "https://www.proxy-source.com/http/",
    "https://www.proxy-source.com/https/",
    "https://www.proxy-source.com/socks4/",
    "https://www.proxy-source.com/socks5/",
    "https://www.proxy-realm.net/http/",
    "https://www.proxy-realm.net/https/",
    "https://www.proxy-realm.net/socks4/",
    "https://www.proxy-realm.net/socks5/",
    "https://www.proxy-dome.net/http/",
    "https://www.proxy-dome.net/https/",
    "https://www.proxy-dome.net/socks4/",
    "https://www.proxy-dome.net/socks5/",
    "https://www.proxy-globe.com/http/",
    "https://www.proxy-globe.com/https/",
    "https://www.proxy-globe.com/socks4/",
    "https://www.proxy-globe.com/socks5/",
    "https://www.proxy-matrix.com/http/",
    "https://www.proxy-matrix.com/https/",
    "https://www.proxy-matrix.com/socks4/",
    "https://www.proxy-matrix.com/socks5/",
    "https://www.proxy-horizon.net/http/",
    "https://www.proxy-horizon.net/https/",
    "https://www.proxy-horizon.net/socks4/",
    "https://www.proxy-horizon.net/socks5/",
    "https://www.proxy-list.download/api/v1/get?type=http"
"https://www.proxy-list.download/api/v1/get?type=https"
"https://www.proxy-list.download/api/v1/get?type=socks4"
"https://www.proxy-list.download/api/v1/get?type=socks5"
"https://www.proxyscrape.com/api/v2/?request=displayproxies&proxytype=http"
"https://www.proxyscrape.com/api/v2/?request=displayproxies&proxytype=https"
"https://www.proxyscrape.com/api/v2/?request=getproxies&protocol=socks4"
"https://www.proxyscrape.com/api/v2/?request=getproxies&protocol=socks5"
"https://api.proxyscrape.com/v2/?request=displayproxies&proxytype=http"
"https://api.proxyscrape.com/v2/?request=displayproxies&proxytype=https"
"https://api.proxyscrape.com/v2/?request=getproxies&protocol=socks4"
"https://api.proxyscrape.com/v2/?request=getproxies&protocol=socks5"
"https://www.free-proxy-list.net/"
"https://www.free-proxy-list.net/https-proxy.html"
"https://www.free-proxy-list.net/socks5-proxy.html"
"https://www.free-proxy-list.net/socks4-proxy.html"
"https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/http.txt"
"https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/https.txt"
"https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/http.txt"
"https://raw.githubusercontent.com/TheSpeedX/SOCKS-List/master/socks5.txt"
"https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies.txt"
"https://raw.githubusercontent.com/hookzof/socks5_list/master/proxy.txt"
"https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/http.txt"
"https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/socks5.txt"
"https://raw.githubusercontent.com/Firdoxx/proxy-list/main/http"
"https://raw.githubusercontent.com/Firdoxx/proxy-list/main/https"
"https://proxymesh.com/api/proxies"
"https://proxyspace.pro/http.txt"
"https://proxy-spider.com/api/proxies.example.txt"
"https://multiproxy.org/txt_all/proxy.txt"
"https://www.proxydocker.com/en/proxylist/download?email=noshare&country=all&city=all&port=all&type=all&anonymity=all&state=all&need=all"
"https://api.proxyscrape.com/v2/?request=displayproxies"
"https://proxyspace.pro/http.txt"
"http://rootjazz.com/proxies/proxies.txt"
"http://alexa.lr2b.com/proxylist.txt"
"https://api.openproxylist.xyz/http.txt"
"http://worm.rip/http.txt"
"https://spys.one/en/http-proxy-list/"
"https://spys.one/en/https-proxy-list/"
"https://spys.one/en/socks5-proxy-list/"
"https://proxymesh.com/api/proxies/socks5"
"https://proxymesh.com/api/proxies/socks4"
"https://www.proxy-list.download/api/v1/get?type=http"
"https://www.proxy-list.download/api/v1/get?type=https"
"https://www.proxy-list.download/api/v1/get?type=socks5"
"https://www.proxy-list.download/api/v1/get?type=socks4"
"https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/http.txt"
"https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/socks5.txt"
"https://raw.githubusercontent.com/Firdoxx/proxy-list/main/http"
"https://raw.githubusercontent.com/Firdoxx/proxy-list/main/https"
"https://proxymesh.com/api/proxies/http"
"https://proxymesh.com/api/proxies/https"
"https://proxymesh.com/api/proxies/socks5"
"https://proxymesh.com/api/proxies/socks4"
"https://proxyspace.pro/http.txt"
"https://proxyspace.pro/https.txt"
"https://proxyspace.pro/socks4.txt"
"https://proxyspace.pro/socks5.txt"
"https://multiproxy.org/txt_all/proxy.txt"
"https://multiproxy.org/txt_all/https.txt"
"https://multiproxy.org/txt_all/socks4.txt"
"https://multiproxy.org/txt_all/socks5.txt"
"https://www.proxydocker.com/en/proxylist/download?email=noshare&country=all&city=all&port=all&type=all&anonymity=all&state=all&need=all"
"https://www.proxydocker.com/en/proxylist/download?email=noshare&country=all&city=all&port=all&type=socks4&anonymity=all&state=all&need=all"
"https://www.proxydocker.com/en/proxylist/download?email=noshare&country=all&city=all&port=all&type=socks5&anonymity=all&state=all&need=all"
"https://spys.one/en/http-proxy-list/"
"https://spys.one/en/https-proxy-list/"
"https://spys.one/en/socks4-proxy-list/"
"https://spys.one/en/socks5-proxy-list/"
"https://api.proxyscrape.com/v2/?request=displayproxies&proxytype=http"
"https://api.proxyscrape.com/v2/?request=displayproxies&proxytype=https"
"https://api.proxyscrape.com/v2/?request=displayproxies&proxytype=socks4"
"https://api.proxyscrape.com/v2/?request=displayproxies&proxytype=socks5"
"http://rootjazz.com/proxies/proxies.txt"
"http://rootjazz.com/proxies/https.txt"
"http://rootjazz.com/proxies/socks4.txt"
"http://rootjazz.com/proxies/socks5.txt"
"http://alexa.lr2b.com/proxylist.txt"
"http://alexa.lr2b.com/httpslist.txt"
"http://alexa.lr2b.com/socks5list.txt"
"http://alexa.lr2b.com/socks4list.txt"
"http://proxymesh.com/api/proxies/http"
"http://proxymesh.com/api/proxies/https"
"http://proxymesh.com/api/proxies/socks5"
"http://proxymesh.com/api/proxies/socks4"
"http://proxyspace.pro/http.txt"
"http://proxyspace.pro/https.txt"
"http://proxyspace.pro/socks4.txt"
"http://proxyspace.pro/socks5.txt"
"http://multiproxy.org/txt_all/proxy.txt"
"http://multiproxy.org/txt_all/https.txt"
"http://multiproxy.org/txt_all/socks4.txt"
"http://multiproxy.org/txt_all/socks5.txt"
"http://www.proxydocker.com/en/proxylist/download?email=noshare&country=all&city=all&port=all&type=all&anonymity=all&state=all&need=all"
"http://www.proxydocker.com/en/proxylist/download?email=noshare&country=all&city=all&port=all&type=socks4&anonymity=all&state=all&need=all"
"http://www.proxydocker.com/en/proxylist/download?email=noshare&country=all&city=all&port=all&type=socks5&anonymity=all&state=all&need=all"
"http://spys.one/en/http-proxy-list/"
"http://spys.one/en/https-proxy-list/"
"http://spys.one/en/socks4-proxy-list/"
"http://spys.one/en/socks5-proxy-list/"
"http://api.proxyscrape.com/v2/?request=displayproxies&proxytype=http"
"http://api.proxyscrape.com/v2/?request=displayproxies&proxytype=https"
"http://api.proxyscrape.com/v2/?request=displayproxies&proxytype=socks4"
"http://api.proxyscrape.com/v2/?request=displayproxies&proxytype=socks5"
"http://rootjazz.com/proxies/proxies.txt"
"http://rootjazz.com/proxies/https.txt"
"http://rootjazz.com/proxies/socks4.txt"
"http://rootjazz.com/proxies/socks5.txt"
"http://alexa.lr2b.com/proxylist.txt"
"http://alexa.lr2b.com/httpslist.txt"
"http://alexa.lr2b.com/socks5list.txt"
"http://alexa.lr2b.com/socks4list.txt"
"http://proxymesh.com/api/proxies/http"
"http://proxymesh.com/api/proxies/https"
"http://proxymesh.com/api/proxies/socks5"
"http://proxymesh.com/api/proxies/socks4"
"http://proxyspace.pro/http.txt"
"http://proxyspace.pro/https.txt"
"http://proxyspace.pro/socks4.txt"
"http://proxyspace.pro/socks5.txt"
"http://multiproxy.org/txt_all/proxy.txt"
"http://multiproxy.org/txt_all/https.txt"
"http://multiproxy.org/txt_all/socks4.txt"
"http://multiproxy.org/txt_all/socks5.txt"
"http://www.proxydocker.com/en/proxylist/download?email=noshare&country=all&city=all&port=all&type=all&anonymity=all&state=all&need=all"
"http://www.proxydocker.com/en/proxylist/download?email=noshare&country=all&city=all&port=all&type=socks4&anonymity=all&state=all&need=all"
"http://www.proxydocker.com/en/proxylist/download?email=noshare&country=all&city=all&port=all&type=socks5&anonymity=all&state=all&need=all"
"https://www.proxy-list.download/api/v1/get?type=http"
"https://www.proxy-list.download/api/v1/get?type=https"
"https://www.proxy-list.download/api/v1/get?type=socks4"
"https://www.proxy-list.download/api/v1/get?type=socks5"
"https://www.proxyscrape.com/api/v2/?request=displayproxies&proxytype=http"
"https://www.proxyscrape.com/api/v2/?request=displayproxies&proxytype=https"
"https://www.proxyscrape.com/api/v2/?request=getproxies&protocol=socks4"
"https://www.proxyscrape.com/api/v2/?request=getproxies&protocol=socks5"
"https://api.proxyscrape.com/v2/?request=displayproxies&proxytype=http"
"https://api.proxyscrape.com/v2/?request=displayproxies&proxytype=https"
"https://api.proxyscrape.com/v2/?request=getproxies&protocol=socks4"
"https://api.proxyscrape.com/v2/?request=getproxies&protocol=socks5"
"https://www.free-proxy-list.net/"
"https://www.free-proxy-list.net/https-proxy.html"
"https://www.free-proxy-list.net/socks5-proxy.html"
"https://www.free-proxy-list.net/socks4-proxy.html"
"https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/http.txt"
"https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/https.txt"
"https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/http.txt"
"https://raw.githubusercontent.com/TheSpeedX/SOCKS-List/master/socks5.txt"
"https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies.txt"
"https://raw.githubusercontent.com/hookzof/socks5_list/master/proxy.txt"
"https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/http.txt"
"https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/socks5.txt"
"https://raw.githubusercontent.com/Firdoxx/proxy-list/main/http"
"https://raw.githubusercontent.com/Firdoxx/proxy-list/main/https"
"https://proxymesh.com/api/proxies"
"https://proxyspace.pro/http.txt"
"https://proxy-spider.com/api/proxies.example.txt"
"https://multiproxy.org/txt_all/proxy.txt"
"https://www.proxydocker.com/en/proxylist/download?email=noshare&country=all&city=all&port=all&type=all&anonymity=all&state=all&need=all"
"https://api.proxyscrape.com/v2/?request=displayproxies"
"https://proxyspace.pro/http.txt"
"http://rootjazz.com/proxies/proxies.txt"
"http://alexa.lr2b.com/proxylist.txt"
"https://api.openproxylist.xyz/http.txt"
"http://worm.rip/http.txt"
"https://spys.one/en/http-proxy-list/"
"https://spys.one/en/https-proxy-list/"
"https://spys.one/en/socks5-proxy-list/"
"https://proxymesh.com/api/proxies/socks5"
"https://proxymesh.com/api/proxies/socks4"
"https://www.proxy-list.download/api/v1/get?type=http"
"https://www.proxy-list.download/api/v1/get?type=https"
"https://www.proxy-list.download/api/v1/get?type=socks5"
"https://www.proxy-list.download/api/v1/get?type=socks4"
"https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/http.txt"
"https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/socks5.txt"
"https://raw.githubusercontent.com/Firdoxx/proxy-list/main/http"
"https://raw.githubusercontent.com/Firdoxx/proxy-list/main/https"
"https://proxymesh.com/api/proxies/http"
"https://proxymesh.com/api/proxies/https"
"https://proxymesh.com/api/proxies/socks5"
"https://proxymesh.com/api/proxies/socks4"
"https://proxyspace.pro/http.txt"
"https://proxyspace.pro/https.txt"
"https://proxyspace.pro/socks4.txt"
"https://proxyspace.pro/socks5.txt"
"https://multiproxy.org/txt_all/proxy.txt"
"https://multiproxy.org/txt_all/https.txt"
"https://multiproxy.org/txt_all/socks4.txt"
"https://multiproxy.org/txt_all/socks5.txt"
"https://www.proxydocker.com/en/proxylist/download?email=noshare&country=all&city=all&port=all&type=all&anonymity=all&state=all&need=all"
"https://www.proxydocker.com/en/proxylist/download?email=noshare&country=all&city=all&port=all&type=socks4&anonymity=all&state=all&need=all"
"https://www.proxydocker.com/en/proxylist/download?email=noshare&country=all&city=all&port=all&type=socks5&anonymity=all&state=all&need=all"
"https://spys.one/en/http-proxy-list/"
"https://spys.one/en/https-proxy-list/"
"https://spys.one/en/socks4-proxy-list/"
"https://spys.one/en/socks5-proxy-list/"
"https://api.proxyscrape.com/v2/?request=displayproxies&proxytype=http"
"https://api.proxyscrape.com/v2/?request=displayproxies&proxytype=https"
"https://api.proxyscrape.com/v2/?request=displayproxies&proxytype=socks4"
"https://api.proxyscrape.com/v2/?request=displayproxies&proxytype=socks5"
"http://rootjazz.com/proxies/proxies.txt"
"http://rootjazz.com/proxies/https.txt"
"http://rootjazz.com/proxies/socks4.txt"
"http://rootjazz.com/proxies/socks5.txt"
"http://alexa.lr2b.com/proxylist.txt"
"http://alexa.lr2b.com/httpslist.txt"
"http://alexa.lr2b.com/socks5list.txt"
"http://alexa.lr2b.com/socks4list.txt"
"http://proxymesh.com/api/proxies/http"
"http://proxymesh.com/api/proxies/https"
"http://proxymesh.com/api/proxies/socks5"
"http://proxymesh.com/api/proxies/socks4"
"http://proxyspace.pro/http.txt"
"http://proxyspace.pro/https.txt"
"http://proxyspace.pro/socks4.txt"
"http://proxyspace.pro/socks5.txt"
"http://multiproxy.org/txt_all/proxy.txt"
"http://multiproxy.org/txt_all/https.txt"
"http://multiproxy.org/txt_all/socks4.txt"
"http://multiproxy.org/txt_all/socks5.txt"
"http://www.proxydocker.com/en/proxylist/download?email=noshare&country=all&city=all&port=all&type=all&anonymity=all&state=all&need=all"
"http://www.proxydocker.com/en/proxylist/download?email=noshare&country=all&city=all&port=all&type=socks4&anonymity=all&state=all&need=all"
"http://www.proxydocker.com/en/proxylist/download?email=noshare&country=all&city=all&port=all&type=socks5&anonymity=all&state=all&need=all"
"https://www.proxy-list.download/api/v1/get?type=http"
"https://www.proxy-list.download/api/v1/get?type=https"
"https://www.proxy-list.download/api/v1/get?type=socks4"
"https://www.proxy-list.download/api/v1/get?type=socks5"
"https://www.proxyscrape.com/api/v2/?request=displayproxies&proxytype=http"
"https://www.proxyscrape.com/api/v2/?request=displayproxies&proxytype=https"
"https://www.proxyscrape.com/api/v2/?request=getproxies&protocol=socks4"
"https://www.proxyscrape.com/api/v2/?request=getproxies&protocol=socks5"
"https://api.proxyscrape.com/v2/?request=displayproxies&proxytype=http"
"https://api.proxyscrape.com/v2/?request=displayproxies&proxytype=https"
"https://api.proxyscrape.com/v2/?request=getproxies&protocol=socks4"
"https://api.proxyscrape.com/v2/?request=getproxies&protocol=socks5"
"https://www.free-proxy-list.net/"
"https://www.free-proxy-list.net/https-proxy.html"
"https://www.free-proxy-list.net/socks5-proxy.html"
"https://www.free-proxy-list.net/socks4-proxy.html"
"https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/http.txt"
"https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/https.txt"
"https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/http.txt"
"https://raw.githubusercontent.com/TheSpeedX/SOCKS-List/master/socks5.txt"
"https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies.txt"
"https://raw.githubusercontent.com/hookzof/socks5_list/master/proxy.txt"
"https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/http.txt"
"https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/socks5.txt"
"https://raw.githubusercontent.com/Firdoxx/proxy-list/main/http"
"https://raw.githubusercontent.com/Firdoxx/proxy-list/main/https"
"https://proxymesh.com/api/proxies"
"https://proxyspace.pro/http.txt"
"https://proxy-spider.com/api/proxies.example.txt"
"https://multiproxy.org/txt_all/proxy.txt"
"https://www.proxydocker.com/en/proxylist/download?email=noshare&country=all&city=all&port=all&type=all&anonymity=all&state=all&need=all"
"https://api.proxyscrape.com/v2/?request=displayproxies"
"https://proxyspace.pro/http.txt"
"http://rootjazz.com/proxies/proxies.txt"
"http://alexa.lr2b.com/proxylist.txt"
"https://api.openproxylist.xyz/http.txt"
"http://worm.rip/http.txt"
"https://spys.one/en/http-proxy-list/"
"https://spys.one/en/https-proxy-list/"
"https://spys.one/en/socks5-proxy-list/"
"https://proxymesh.com/api/proxies/socks5"
"https://proxymesh.com/api/proxies/socks4"
"https://www.proxy-list.download/api/v1/get?type=http"
"https://www.proxy-list.download/api/v1/get?type=https"
"https://www.proxy-list.download/api/v1/get?type=socks5"
"https://www.proxy-list.download/api/v1/get?type=socks4"
"https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/http.txt"
"https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/socks5.txt"
"https://raw.githubusercontent.com/Firdoxx/proxy-list/main/http"
"https://raw.githubusercontent.com/Firdoxx/proxy-list/main/https"
"https://proxymesh.com/api/proxies/http"
"https://proxymesh.com/api/proxies/https"
"https://proxymesh.com/api/proxies/socks5"
"https://proxymesh.com/api/proxies/socks4"
"https://proxyspace.pro/http.txt"
"https://proxyspace.pro/https.txt"
"https://proxyspace.pro/socks4.txt"
"https://proxyspace.pro/socks5.txt"
"https://multiproxy.org/txt_all/proxy.txt"
"https://multiproxy.org/txt_all/https.txt"
"https://multiproxy.org/txt_all/socks4.txt"
"https://multiproxy.org/txt_all/socks5.txt"
"https://www.proxydocker.com/en/proxylist/download?email=noshare&country=all&city=all&port=all&type=all&anonymity=all&state=all&need=all"
"https://www.proxydocker.com/en/proxylist/download?email=noshare&country=all&city=all&port=all&type=socks4&anonymity=all&state=all&need=all"
"https://www.proxydocker.com/en/proxylist/download?email=noshare&country=all&city=all&port=all&type=socks5&anonymity=all&state=all&need=all"
"https://spys.one/en/http-proxy-list/"
"https://spys.one/en/https-proxy-list/"
"https://spys.one/en/socks4-proxy-list/"
"https://spys.one/en/socks5-proxy-list/"
"https://api.proxyscrape.com/v2/?request=displayproxies&proxytype=http"
"https://api.proxyscrape.com/v2/?request=displayproxies&proxytype=https"
"https://api.proxyscrape.com/v2/?request=displayproxies&proxytype=socks4"
"https://api.proxyscrape.com/v2/?request=displayproxies&proxytype=socks5"
"http://rootjazz.com/proxies/proxies.txt"
"http://rootjazz.com/proxies/https.txt"
"http://rootjazz.com/proxies/socks4.txt"
"http://rootjazz.com/proxies/socks5.txt"
"http://alexa.lr2b.com/proxylist.txt"
"http://alexa.lr2b.com/httpslist.txt"
"http://alexa.lr2b.com/socks5list.txt"
"http://alexa.lr2b.com/socks4list.txt"
"http://proxymesh.com/api/proxies/http"
"http://proxymesh.com/api/proxies/https"
"http://proxymesh.com/api/proxies/socks5"
"http://proxymesh.com/api/proxies/socks4"
"http://proxyspace.pro/http.txt"
"http://proxyspace.pro/https.txt"
"http://proxyspace.pro/socks4.txt"
"http://proxyspace.pro/socks5.txt"
"http://multiproxy.org/txt_all/proxy.txt"
"http://multiproxy.org/txt_all/https.txt"
"http://multiproxy.org/txt_all/socks4.txt"
"http://multiproxy.org/txt_all/socks5.txt"
"http://www.proxydocker.com/en/proxylist/download?email=noshare&country=all&city=all&port=all&type=all&anonymity=all&state=all&need=all"
"http://www.proxydocker.com/en/proxylist/download?email=noshare&country=all&city=all&port=all&type=socks4&anonymity=all&state=all&need=all"
"http://www.proxydocker.com/en/proxylist/download?email=noshare&country=all&city=all&port=all&type=socks5&anonymity=all&state=all&need=all"
"https://www.proxy-list.download/api/v1/get?type=http"
"https://www.proxy-list.download/api/v1/get?type=https"
"https://www.proxy-list.download/api/v1/get?type=socks4"
"https://www.proxy-list.download/api/v1/get?type=socks5"
"https://www.proxyscrape.com/api/v2/?request=displayproxies&proxytype=http"
"https://www.proxyscrape.com/api/v2/?request=displayproxies&proxytype=https"
"https://www.proxyscrape.com/api/v2/?request=getproxies&protocol=socks4"
"https://www.proxyscrape.com/api/v2/?request=getproxies&protocol=socks5"
"https://api.proxyscrape.com/v2/?request=displayproxies&proxytype=http"
"https://api.proxyscrape.com/v2/?request=displayproxies&proxytype=https"
"https://api.proxyscrape.com/v2/?request=getproxies&protocol=socks4"
"https://api.proxyscrape.com/v2/?request=getproxies&protocol=socks5"
"https://www.free-proxy-list.net/"
"https://www.free-proxy-list.net/https-proxy.html"
"https://www.free-proxy-list.net/socks5-proxy.html"
"https://www.free-proxy-list.net/socks4-proxy.html"
"https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/http.txt"
"https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/https.txt"
"https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/http.txt"
"https://raw.githubusercontent.com/TheSpeedX/SOCKS-List/master/socks5.txt"
"https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies.txt"
"https://raw.githubusercontent.com/hookzof/socks5_list/master/proxy.txt"
"https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/http.txt"
"https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/socks5.txt"
"https://raw.githubusercontent.com/Firdoxx/proxy-list/main/http"
"https://raw.githubusercontent.com/Firdoxx/proxy-list/main/https"
"https://proxymesh.com/api/proxies"
"https://proxyspace.pro/http.txt"
"https://proxy-spider.com/api/proxies.example.txt"
"https://multiproxy.org/txt_all/proxy.txt"
"https://www.proxydocker.com/en/proxylist/download?email=noshare&country=all&city=all&port=all&type=all&anonymity=all&state=all&need=all"
"https://api.proxyscrape.com/v2/?request=displayproxies"
"https://proxyspace.pro/http.txt"
"http://rootjazz.com/proxies/proxies.txt"
"http://alexa.lr2b.com/proxylist.txt"
"https://api.openproxylist.xyz/http.txt"
"http://worm.rip/http.txt"
"https://spys.one/en/http-proxy-list/"
"https://spys.one/en/https-proxy-list/"
"https://spys.one/en/socks5-proxy-list/"
"https://proxymesh.com/api/proxies/socks5"
"https://proxymesh.com/api/proxies/socks4"
"https://www.proxy-list.download/api/v1/get?type=http"
"https://www.proxy-list.download/api/v1/get?type=https"
"https://www.proxy-list.download/api/v1/get?type=socks5"
"https://www.proxy-list.download/api/v1/get?type=socks4"
"https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/http.txt"
"https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/socks5.txt"
"https://raw.githubusercontent.com/Firdoxx/proxy-list/main/http"
"https://raw.githubusercontent.com/Firdoxx/proxy-list/main/https"
"https://proxymesh.com/api/proxies/http"
"https://proxymesh.com/api/proxies/https"
"https://proxymesh.com/api/proxies/socks5"
"https://proxymesh.com/api/proxies/socks4"
"https://proxyspace.pro/http.txt"
"https://proxyspace.pro/https.txt"
"https://proxyspace.pro/socks4.txt"
"https://proxyspace.pro/socks5.txt"
"https://multiproxy.org/txt_all/proxy.txt"
"https://multiproxy.org/txt_all/https.txt"
"https://multiproxy.org/txt_all/socks4.txt"
"https://multiproxy.org/txt_all/socks5.txt"
"https://www.proxydocker.com/en/proxylist/download?email=noshare&country=all&city=all&port=all&type=all&anonymity=all&state=all&need=all"
"https://www.proxydocker.com/en/proxylist/download?email=noshare&country=all&city=all&port=all&type=socks4&anonymity=all&state=all&need=all"
"https://www.proxydocker.com/en/proxylist/download?email=noshare&country=all&city=all&port=all&type=socks5&anonymity=all&state=all&need=all"
"https://spys.one/en/http-proxy-list/"
"https://spys.one/en/https-proxy-list/"
"https://spys.one/en/socks4-proxy-list/"
"https://spys.one/en/socks5-proxy-list/"
"https://api.proxyscrape.com/v2/?request=displayproxies&proxytype=http"
"https://api.proxyscrape.com/v2/?request=displayproxies&proxytype=https"
"https://api.proxyscrape.com/v2/?request=displayproxies&proxytype=socks4"
"https://api.proxyscrape.com/v2/?request=displayproxies&proxytype=socks5"
"http://rootjazz.com/proxies/proxies.txt"
"http://rootjazz.com/proxies/https.txt"
"http://rootjazz.com/proxies/socks4.txt"
"http://rootjazz.com/proxies/socks5.txt"
"http://alexa.lr2b.com/proxylist.txt"
"http://alexa.lr2b.com/httpslist.txt"
"http://alexa.lr2b.com/socks5list.txt"
"http://alexa.lr2b.com/socks4list.txt"
"http://proxymesh.com/api/proxies/http"
"http://proxymesh.com/api/proxies/https"
"http://proxymesh.com/api/proxies/socks5"
"http://proxymesh.com/api/proxies/socks4"
"http://proxyspace.pro/http.txt"
"http://proxyspace.pro/https.txt"
"http://proxyspace.pro/socks4.txt"
"http://proxyspace.pro/socks5.txt"
"http://multiproxy.org/txt_all/proxy.txt"
"http://multiproxy.org/txt_all/https.txt"
"http://multiproxy.org/txt_all/socks4.txt"
"http://multiproxy.org/txt_all/socks5.txt"
"http://www.proxydocker.com/en/proxylist/download?email=noshare&country=all&city=all&port=all&type=all&anonymity=all&state=all&need=all"
"http://www.proxydocker.com/en/proxylist/download?email=noshare&country=all&city=all&port=all&type=socks4&anonymity=all&state=all&need=all"
"http://www.proxydocker.com/en/proxylist/download?email=noshare&country=all&city=all&port=all&type=socks5&anonymity=all&state=all&need=all"
    "https://www.proxy-guru.net/http/",
    "https://www.proxy-guru.net/https/",
    "https://www.proxy-guru.net/socks4/",
    "https://www.proxy-guru.net/socks5/",
    "https://www.proxy-tech.net/http/",
    "https://www.proxy-tech.net/https/",
    "https://www.proxy-tech.net/socks4/",
    "https://www.proxy-tech.net/socks5/"
]



# Mengambil proxy dari setiap URL
def fetch_proxies(url):
    try:
        response = requests.get(url)
        return response.text.splitlines()
    except requests.RequestException as e:
        print(f"Error fetching proxies from {url}: {e}")
        return []

def main():
    all_proxies = []
    for url in proxy_urls:
        proxies = fetch_proxies(url)
        all_proxies.extend(proxies)
    
    # Menghilangkan duplikat
    unique_proxies = set(all_proxies)
    
    with open("proxy.txt", "w") as file:
        for proxy in unique_proxies:
            file.write(f"{proxy}\n")

    print(f"Fetched {len(unique_proxies)} unique proxies.")

if __name__ == "__main__":
    main()
